name: Docs

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2

      - run: zig build-lib root.zig -femit-docs

      - run: |
          mkdir -p public
          cp -r docs/* public/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4